export interface IEvent {
  passwordProtected: boolean
  passwordAuthenticated: boolean
  name: string
  description?: string
  slug: string
  redirectUrl?: string
  facebookEvent?: string
  title: string
  relatedProducts: []
  country: string
  date: string
  startDate: string
  endDate: string
  timezone: string
  formattedDate: string
  venueCountry: string
  venueCity?: string
  venueState?: string
  hideVenueUntil?: string
  hideVenue?: boolean
  venueName?: string
  venueGooglePlaceId?: string
  venueLatitude?: string
  venueLongitude?: string
  venuePostalCode?: string
  venueStreet?: string
  venueStreetNumber?: string
  eventType: any
  productImage: string
  imageUrl: string
  imageUrlHd: string
  backgroundImage: string
  backgroundVideo?: string
  twitterImage?: string
  ogImage?: string
  tags: []
  preregEnabled: boolean
  presalesStarted: boolean
  presalesEnded: boolean
  salesStart?: string
  salesEnd: string
  salesStarted: boolean
  salesEnded: boolean
  feeMode: string
  feesIncluded?: any
  minimumAge?: any
  enableWaitingList: boolean
  alwaysShowWaitingList?: any
  titleReplacementImage?: any
  titleReplacementHeight?: any
  titleReplacementImageSvg?: any
  fullTitleReplacement?: any
  affirmAllowed: boolean
  subHeading?: any
  isTimeSlotEvent: boolean
  preregistered: []
  referralsEnabled: boolean
  referrals: []
  faq: []
  l10nLanguages: []
  imageURLs: any
  descriptions: any
}

export interface IEventData {
  slug: string
  name: string
  description?: string
  title: string
}
